import { useState } from 'react'

/**
 * Responsive portrait: AVIF → WebP → JPEG with srcset, generated by
 * `npm run photo`. Falls back to a stylised placeholder until a photo exists.
 */
export default function Portrait({ base, alt, className = '', sizes = '(min-width: 1024px) 50vw, 100vw' }) {
  const [failed, setFailed] = useState(false)
  const set = (ext) => `${base}-640.${ext} 640w, ${base}-1080.${ext} 1080w, ${base}-1600.${ext} 1600w`

  if (failed)
    return (
      <div className={`flex items-center justify-center bg-ink-3/40 ${className}`}>
        <pre className="text-center font-mono text-[11px] leading-5 text-dim">
          {`   .-""""-.\n  /        \\\n |  o    o  |\n |    __    |\n  \\  '--'  /\n   '-....-'\n\n`}
          <span className="text-acid">$</span> npm run photo
        </pre>
      </div>
    )

  return (
    <picture>
      <source type="image/avif" srcSet={set('avif')} sizes={sizes} />
      <source type="image/webp" srcSet={set('webp')} sizes={sizes} />
      <img
        src={`${base}-1080.jpg`}
        alt={alt}
        sizes={sizes}
        fetchPriority="high"
        decoding="async"
        onError={() => setFailed(true)}
        className={className}
      />
    </picture>
  )
}
